version: '3'
services:
  web:
    container_name: do-test-web-container
    build: .
    ports:
      - '8080:3000'
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      DATABASE_URL: 'postgres://docker:docker@postgres/dotestdb'
  postgres:
    container_name: do-test-postgres-container
    image: 'postgres:alpine'
    ports:
      - '5432:5432'
    volumes:
      - 'e:/postgres-data:/var/lib/postgresql/data/pgdata'
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: dotestdb
      PGDATA: /var/lib/postgresql/data/pgdata
